import Banner from '@/components/Banner';
import Footer from '@/components/Footer';
import Header from '@/components/Header/Header';
import { type NextPage } from 'next';
import Head from 'next/head';
import 'react-date-range/dist/styles.css'; // main style file
import 'react-date-range/dist/theme/default.css'; // theme css file
import toast, { Toaster } from 'react-hot-toast';

const Home: NextPage = () => {
  const notify = () => toast.success('Here is your toast.');

  return (
    <>
      <Head>
        <title>Car rental App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Toaster />
      <main className='bg-gray-primary max-w-7xl mx-auto'>
        <Header />
        <Banner />
      </main>
      <main className='mx-auto max-w-7xl px-8 sm:px-16'>
        <Footer />
      </main>
    </>
  );
};

export default Home;
